### ISSUE TITLE
Add value for RosSystem Parameters qa_energy y qa_safety

### ISSUE THREAD

**Issue by chcorbato** [rosin-project/rosin-experiments#12]
We need to add the values according to this table: [spreadsheet](https://docs.google.com/spreadsheets/d/12aB35Jj4qmarIq3OWHocATmnDfUa6ftp_j09W5twy1g/edit#gid=1715992839)
and this [suggestion](https://github.com/rosin-project/mros1_reasoner/issues/10#issuecomment-632673381)
qa_energy = [QA energy Max](https://docs.google.com/spreadsheets/d/12aB35Jj4qmarIq3OWHocATmnDfUa6ftp_j09W5twy1g/edit#gid=1715992839&range=F:F)
qa_safety = [QA Safety Min](https://docs.google.com/spreadsheets/d/12aB35Jj4qmarIq3OWHocATmnDfUa6ftp_j09W5twy1g/edit#gid=1715992839&range=I:I)

**Comment by NadiaHG** [comment]
Done: https://github.com/rosin-project/metacontrol_move_base_configurations/pull/5

Additionally I modified the generator script to include the values, I am not sure if this modification should be merged... https://github.com/rosin-project/rosin-experiments/pull/15 , but for now it can be useful in case we have to adjust a value. 

-----

How to guide:

Current process to autogenerate all the roslaunch packages:
```
cd 
mkdir rosin-experiment
cd rosin-experiment
git clone https://github.com/rosin-project/rosin-experiments/
git clone https://github.com/rosin-project/metacontrol_move_base_configurations
cd rosin-experiments/metacontrol_models_experiment/MoveBaseConfigurations
./create_config_combination_move_base.sh
```
The last command will create a folder that includes a rossystem file for each configuration under `rosin-experiments/metacontrol_models_experiment/src-gen` .

Open the ROS tooling (latest release version from May 20th) , press the ["import common ROS objects" button ](https://github.com/seronet-project/SeRoNet-examples/blob/master/SeRoNet-Tooling-ROS-Mixed-Port/ROS-MixedPort-Examples/ROSMixedPortTutorials_WSsetup.md#ros-workspace-setup) and import the project: rosin-experiments/metacontrol_models_experiment/.

Automatically the ROS deployable artifacts for all your rossystem configuration will be created, that for the current version of the ROS tooling this means a rospackage that includes a launch file.

```
cd rosin-experiments/metacontrol_models_experiment/src-gen
cp f*_v*_r* ../../../metacontrol_move_base_configurations -rf
cd ../../../metacontrol_move_base_configurations
git checkout -b NewConfigs
git commit -am "new auto-genarted rossystem and launch files"
git push origin NewConfigs
```
-> OPEN a PR to https://github.com/rosin-project/metacontrol_move_base_configurations

**Comment by chcorbato** [comment]
Awesome. 

> How to guide:

This **How to guide** is excellent and very valuable, could you please add this guide in a README file. There is quite some information in issues and pull requests that later I find it difficult to find.

**Comment by NadiaHG** [comment]
The general documentation was already available : https://github.com/rosin-project/rosin-experiments/tree/master/metacontrol_models_experiment#function-designs-models-for-move_base 

The commands related to this particular experiment (about where to copy the autogenerated files to push them to GitHub) will be added to the [metacontrol_move_base_configurations](https://github.com/rosin-project/metacontrol_move_base_configurations).

Issue created -> https://github.com/rosin-project/metacontrol_move_base_configurations/issues/6

**Comment by chcorbato** [comment]
Great! The I close this issue then.
