### ISSUE TITLE
[RosModel] Define a consistent architecture to define multi-layer subsets of components

### ISSUE THREAD

**Issue by NadiaHG** [rosin-project/rosin-experiments#19]
We should find a models structure to "split" the components that compose a system depending on the functionality. For example : 1) set of the low-level driver components, 2) set of components required to localize the robot and 3) set of components required to navigate. 

This split is supported by the metacontrol, the idea is to be able to describe the same hierarchy using the ROS-models and use the [rosmodel2owl script](https://github.com/tud-cor/mc_mros_reasoner) to auto-generate a owl file with the proper layers structure. For the experiment we planned to use the laser scanner as a component required to localize the robot. For this scanner we have also to add functional properties (ros global parameters for ROS model) to detect anomalies of its output data (values out of the range or low publisher frequency).

--------

NOTE:
previous ROS model efforts made in this direction, lightly related: 
- capabilities checker: https://github.com/ipa-nhg/ros-model-experiments/blob/cob4/cob4-25/cob4-25_monitoring/cob4-25_navigation.rossystem , with this file we evaluate if a system is suitable to run a standard navigation stack. Only check interfaces.
- desired components: https://github.com/ipa-nhg/ros-model-experiments/blob/cob4/cob4-25/cob4-25_monitoring/cob4-25_desired_components.rossystem , this file was created to diagnose a Care-O-bot. Given the file as input to the rosgraph_monitor we will get automatically a diagnosis error message if one of this nodes is down.

**Comment by chcorbato** [comment]
This is related to https://github.com/rosin-project/metacontrol_models_paper/issues/36 ([RosModel] Explore the possibility of supporting groups of components with the rossytem model)
maybe we should close this issue @ipa-nhg

**Comment by NadiaHG** [comment]
superseded by https://github.com/rosin-project/metacontrol_models_paper/issues/36
